//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinarApp.DesktopClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BinarApp.DesktopClient.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAPID.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateTable {
            get {
                return ResourceManager.GetString("DateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DescriptionDetail {
            get {
                return ResourceManager.GetString("DescriptionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by description:.
        /// </summary>
        public static string DescriptionSearchLabel {
            get {
                return ResourceManager.GetString("DescriptionSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionTable {
            get {
                return ResourceManager.GetString("DescriptionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter login.
        /// </summary>
        public static string EnterNicknameText {
            get {
                return ResourceManager.GetString("EnterNicknameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string FormBirthDate {
            get {
                return ResourceManager.GetString("FormBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual input.
        /// </summary>
        public static string FormButton {
            get {
                return ResourceManager.GetString("FormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FormDescription {
            get {
                return ResourceManager.GetString("FormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string FormFirstName {
            get {
                return ResourceManager.GetString("FormFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate number.
        /// </summary>
        public static string FormGRNZ {
            get {
                return ResourceManager.GetString("FormGRNZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string FormLastName {
            get {
                return ResourceManager.GetString("FormLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middlename.
        /// </summary>
        public static string FormMiddleName {
            get {
                return ResourceManager.GetString("FormMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty sum.
        /// </summary>
        public static string FormPenaltySum {
            get {
                return ResourceManager.GetString("FormPenaltySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string FormSendButton {
            get {
                return ResourceManager.GetString("FormSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string FormSpeed {
            get {
                return ResourceManager.GetString("FormSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainButton {
            get {
                return ResourceManager.GetString("MainButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be filled!.
        /// </summary>
        public static string NicknameValidationText {
            get {
                return ResourceManager.GetString("NicknameValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string NoDataText {
            get {
                return ResourceManager.GetString("NoDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrol mode.
        /// </summary>
        public static string PatroolButtonText {
            get {
                return ResourceManager.GetString("PatroolButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlateNumber:.
        /// </summary>
        public static string PlateNumberDetail {
            get {
                return ResourceManager.GetString("PlateNumberDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by plate number:.
        /// </summary>
        public static string PlateNumberSearchLabel {
            get {
                return ResourceManager.GetString("PlateNumberSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlateNumber.
        /// </summary>
        public static string PlateNumberTable {
            get {
                return ResourceManager.GetString("PlateNumberTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        public static string SpeedDetail {
            get {
                return ResourceManager.GetString("SpeedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string SpeedTable {
            get {
                return ResourceManager.GetString("SpeedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification mode.
        /// </summary>
        public static string VerificationButtonText {
            get {
                return ResourceManager.GetString("VerificationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle is wanted!.
        /// </summary>
        public static string WantedText {
            get {
                return ResourceManager.GetString("WantedText", resourceCulture);
            }
        }
    }
}
